export DOCKERNAME="!!MAIN_DOCKER_NAME"
export DOCKER_WP_PORT="8001"
export DOCKER_DB_PORT="9001"
export SERVER_DOMAIN="!!MAIN_DOMAIN"
export ADDITIONAL_DOMAINS="www.!!MAIN_DOMAIN"
export MYSQL_USER="!!MYSQL_USER"
export MYSQL_PASSWORD='!!MYSQL_PASSWORD'
export MYSQL_ROOT_PASSWORD='!!MYSQL_ROOT_PASSWORD'
export MYSQL_DATABASE="!!MYSQL_DATABASE"

# WP_TABLE_PREFIX: short prefix - e.g. wp_
export WP_TABLE_PREFIX=wp_
